"""Remove email and user_type, make username required

Revision ID: 90603c1ae75b
Revises: e81817266d40
Create Date: 2026-06-20 18:50:17.443313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90603c1ae75b'
down_revision: Union[str, Sequence[str], None] = 'e81817266d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'email')
    
    from sqlalchemy.dialects.postgresql import ENUM
    user_type_enum = ENUM('DEAF', 'BLIND', name='usertype', create_type=False)
    user_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects.postgresql import ENUM
    user_type_enum = ENUM('DEAF', 'BLIND', name='usertype', create_type=False)
    user_type_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('user_type', user_type_enum, autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
