"""define sign_phrase columns

Revision ID: b38684fa457d
Revises: a1b2c3d4e5f6
Create Date: 2026-06-20 14:17:16.820222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38684fa457d'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('meetings_code_key', 'meetings', type_='unique')
    op.drop_index('ix_meetings_code', table_name='meetings')
    op.create_index(op.f('ix_meetings_code'), 'meetings', ['code'], unique=True)
    op.add_column('sign_phrases', sa.Column('text', sa.String(), nullable=False))
    op.add_column('sign_phrases', sa.Column('language', sa.String(), nullable=False))
    op.add_column('sign_phrases', sa.Column('avatar_animation_id', sa.Integer(), nullable=False))
    op.add_column('sign_phrases', sa.Column('gesture_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sign_phrases', 'gesture_label')
    op.drop_column('sign_phrases', 'avatar_animation_id')
    op.drop_column('sign_phrases', 'language')
    op.drop_column('sign_phrases', 'text')
    op.drop_index(op.f('ix_meetings_code'), table_name='meetings')
    op.create_index('ix_meetings_code', 'meetings', ['code'], unique=False)
    op.create_unique_constraint('meetings_code_key', 'meetings', ['code'])
    # ### end Alembic commands ###
