"""Update User model

Revision ID: e81817266d40
Revises: 43ac613bf7a2
Create Date: 2026-06-20 18:48:56.926349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81817266d40'
down_revision: Union[str, Sequence[str], None] = '43ac613bf7a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects.postgresql import ENUM
    user_type_enum = ENUM('DEAF', 'BLIND', name='usertype', create_type=False)
    user_type_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('user_type', user_type_enum, nullable=False))
    
    # Need to drop default sequence and alter type using gen_random_uuid() for existing rows (if any)
    op.execute('ALTER TABLE users ALTER COLUMN id DROP DEFAULT')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using='gen_random_uuid()')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('users', 'user_type')
    
    from sqlalchemy.dialects.postgresql import ENUM
    user_type_enum = ENUM('DEAF', 'BLIND', name='usertype', create_type=False)
    user_type_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
